version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: Cantho
  coins:
  - 50000000000000uaura
- name: Vinh
  coins:
  - 50000000000000uaura
- name: Hagiang
  coins:
  - 50000000000000uaura
- name: Thaibinh
  coins:
  - 50000000000000uaura
faucet:
  name: null
  coins: []
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    aura:
      params:
        max_supply: "1000000000000000"
    crisis:
      constant_fee:
        denom: uaura
    gov:
      deposit_params:
        max_deposit_period: 172800s
        min_deposit:
        - amount: "1000000"
          denom: uaura
      voting_params:
        voting_period: 172800s
    mint:
      params:
        blocks_per_year: "5373084"
        inflation_max: "0.120000000000000000"
        inflation_min: "0.040000000000000000"
        inflation_rate_change: "0.080000000000000000"
        mint_denom: uaura
    slashing:
      params:
        downtime_jail_duration: 600s
        signed_blocks_window: "1000"
    smartaccount:
      params:
        disable_msgs_list:
        - /cosmwasm.wasm.v1.MsgUpdateAdmin
        - /cosmwasm.wasm.v1.MsgClearAdmin
        max_gas_execute: 2000000
        whitelist_code_id: []
      smart_account_id: 0
    staking:
      params:
        bond_denom: uaura
        max_validators: 5
        unbonding_time: 86400s
  chain_id: aura-testnet
validators:
- name: Cantho
  bonded: 10000000000uaura
  app:
    minimum-gas-prices: 0.001uaura
