accounts:
  - name: validator
    coins: ["5000000000000uaura"]
    mnemonic: "satisfy adjust timber high purchase tuition stool faith fine install that you unaware feed domain license impose boss human eager hat rent enjoy dawn"
  - name: user1
    coins: ["1000000000000uaura"]
    mnemonic: "notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius"
  - name: user2
    coins: ["1000000000000uaura"]
    mnemonic: "quality vacuum heart guard buzz spike sight swarm shove special gym robust assume sudden deposit grid alcohol choice devote leader tilt noodle tide penalty"
  - name: user3
    coins: ["1000000000000uaura"]
    mnemonic: "symbol force gallery make bulk round subway violin worry mixture penalty kingdom boring survey tool fringe patrol sausage hard admit remember broken alien absorb"
  - name: user4
    coins: ["1000000000000uaura"]
    mnemonic: "bounce success option birth apple portion aunt rural episode solution hockey pencil lend session cause hedgehog slender journey system canvas decorate razor catch empty"
  - name: user5
    coins: ["1000000000000uaura"]
    mnemonic: "	second render cat sing soup reward cluster island bench diet lumber grocery repeat balcony perfect diesel stumble piano distance caught occur example ozone loyal"
  - name: user6
    coins: ["1000000000000uaura"]
    mnemonic: "spatial forest elevator battle also spoon fun skirt flight initial nasty transfer glory palm drama gossip remove fan joke shove label dune debate quick"
  - name: user7
    coins: ["1000000000000uaura"]
    mnemonic: "noble width taxi input there patrol clown public spell aunt wish punch moment will misery eight excess arena pen turtle minimum grain vague inmate"
  - name: user8
    coins: ["1000000000000uaura"]
    mnemonic: "cream sport mango believe inhale text fish rely elegant below earth april wall rug ritual blossom cherry detail length blind digital proof identify ride"
  - name: user9
    coins: ["1000000000000uaura"]
    mnemonic: "index light average senior silent limit usual local involve delay update rack cause inmate wall render magnet common feature laundry exact casual resource hundred"
  - name: user10
    coins: ["1000000000000uaura"]
    mnemonic: "prefer forget visit mistake mixture feel eyebrow autumn shop pair address airport diesel street pass vague innocent poem method awful require hurry unhappy shoulder"
validator:
  name: validator
  staked: "100000000uaura"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: validator
  coins: ["50000000uaura"]
init:
  app:
    minimum-gas-prices: "0.0001uaura"
  config:
    consensus:
      timeout_propose: "1s"
      timeout_propose_delta: "500ms"
      timeout_prevote: "1s"
      timeout_prevote_delta: "500ms"
      timeout_precommit: "1s"
      timeout_precommit_delta: "500ms"
      timeout_commit: "1s"
genesis:
  chain_id: "aura-local"
  app_state:
    aura:
      params:
        max_supply: "100000000000000000000000000000"
    crisis:
      constant_fee:
        denom: uaura
    gov:
      deposit_params:
        min_deposit: [
         {
           "denom": "uaura",
           "amount": "10000000"
         }
        ]
        max_deposit_period: "600s"
      voting_params:
        voting_period: "600s"
    mint:
      params:
        mint_denom: "uaura"
    staking:
      params:
        bond_denom: "uaura"