FROM golang:1.18.4-alpine3.15 as builder

ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0-beta7/libwasmvm_muslc.a /lib/libwasmvm_muslc.a
RUN sha256sum /lib/libwasmvm_muslc.a | grep d0152067a5609bfdfb3f0d5d6c0f2760f79d5f2cd7fd8513cafa9932d22eb350

RUN set -eux; apk add --no-cache ca-certificates build-base;

RUN apk add git

COPY . /aura
WORKDIR /aura

RUN make clean && make build VERBOSE=1 BUILD_TAGS=muslc

RUN echo "Ensuring binary is statically linked ..." \
  && (file /aura/build/aurad | grep "statically linked")

FROM golang:1.18.4-bullseye as ignite
ARG BUILD_ENV=dev

RUN curl https://get.ignite.com/cli! | bash

COPY . /aura
WORKDIR /aura

COPY config.${BUILD_ENV}.yml config.yml
RUN ignite chain init

FROM alpine:3.15

COPY --from=ignite /root/.aura /root/.aura
COPY --from=builder /aura/build/aurad /usr/bin/aurad

EXPOSE 1317 4500 26657

CMD ["/usr/bin/aurad", "start"]
