// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smartaccount/account.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SmartAccount is a smart contract that is capable of initiating txs.
//
// This account type is similar to BaseAccount
type SmartAccount struct {
	Address       string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey        *types.Any `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"public_key,omitempty"`
	AccountNumber uint64     `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence      uint64     `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *SmartAccount) Reset()         { *m = SmartAccount{} }
func (m *SmartAccount) String() string { return proto.CompactTextString(m) }
func (*SmartAccount) ProtoMessage()    {}
func (*SmartAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_2859bfbecb22ffc3, []int{0}
}
func (m *SmartAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SmartAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SmartAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SmartAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartAccount.Merge(m, src)
}
func (m *SmartAccount) XXX_Size() int {
	return m.Size()
}
func (m *SmartAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SmartAccount proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SmartAccount)(nil), "auranw.aura.smartaccount.SmartAccount")
}

func init() { proto.RegisterFile("smartaccount/account.proto", fileDescriptor_2859bfbecb22ffc3) }

var fileDescriptor_2859bfbecb22ffc3 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xbd, 0x4e, 0xf3, 0x30,
	0x00, 0x8c, 0xbf, 0xaf, 0x6a, 0x21, 0xfc, 0x0c, 0x51, 0x07, 0x37, 0x42, 0x69, 0x85, 0x84, 0x94,
	0xa1, 0xb5, 0x55, 0xd8, 0xd8, 0xda, 0x01, 0x84, 0x90, 0x18, 0xca, 0xc6, 0x52, 0xd9, 0xa9, 0x49,
	0x2b, 0x1a, 0x3b, 0xc4, 0x36, 0x25, 0x6f, 0xc0, 0xc8, 0x23, 0xf4, 0x21, 0x78, 0x08, 0xc6, 0x8a,
	0x89, 0xa9, 0x42, 0xed, 0x82, 0x78, 0x0a, 0x94, 0xd8, 0x45, 0x30, 0x9d, 0xef, 0x7c, 0x3e, 0xe9,
	0xce, 0xae, 0x2f, 0x13, 0x92, 0x29, 0x12, 0x45, 0x42, 0x73, 0x85, 0x2d, 0xa2, 0x34, 0x13, 0x4a,
	0x78, 0x90, 0xe8, 0x8c, 0xf0, 0x19, 0x2a, 0x00, 0xfd, 0xf6, 0xf9, 0x8d, 0x48, 0xc8, 0x44, 0xc8,
	0x61, 0xe9, 0xc3, 0x86, 0x98, 0x47, 0x7e, 0x3d, 0x16, 0xb1, 0x30, 0x7a, 0x71, 0xb2, 0x6a, 0x23,
	0x16, 0x22, 0x9e, 0x32, 0x5c, 0x32, 0xaa, 0x6f, 0x31, 0xe1, 0xb9, 0xb9, 0x3a, 0x5c, 0x02, 0x77,
	0xf7, 0xba, 0x08, 0xef, 0x99, 0x70, 0x0f, 0xba, 0x35, 0x32, 0x1a, 0x65, 0x4c, 0x4a, 0x08, 0x5a,
	0x20, 0xdc, 0x1e, 0x6c, 0xa8, 0x77, 0xee, 0xd6, 0x52, 0x4d, 0x87, 0x77, 0x2c, 0x87, 0xff, 0x5a,
	0x20, 0xdc, 0x39, 0xae, 0x23, 0x93, 0x8b, 0x36, 0xb9, 0xa8, 0xc7, 0xf3, 0x3e, 0xfc, 0x5a, 0x36,
	0xeb, 0xa9, 0xa6, 0xd3, 0x49, 0x54, 0x78, 0xdb, 0x22, 0x99, 0x28, 0x96, 0xa4, 0x2a, 0x1f, 0x54,
	0x53, 0x4d, 0x2f, 0x59, 0xee, 0x1d, 0xb9, 0xfb, 0xb6, 0xca, 0x90, 0xeb, 0x84, 0xb2, 0x0c, 0xfe,
	0x6f, 0x81, 0xb0, 0x32, 0xd8, 0xb3, 0xea, 0x55, 0x29, 0x7a, 0xbe, 0xbb, 0x25, 0xd9, 0xbd, 0x66,
	0x3c, 0x62, 0xb0, 0x52, 0x1a, 0x7e, 0xf8, 0x69, 0xf8, 0x34, 0x6f, 0x3a, 0x9f, 0xf3, 0xa6, 0xf3,
	0xf6, 0xd2, 0x39, 0xb0, 0x0b, 0x10, 0xad, 0xc6, 0xe8, 0xa1, 0x4b, 0x99, 0x22, 0x5d, 0x64, 0xeb,
	0x5c, 0xf4, 0xcf, 0x5e, 0x57, 0x01, 0x58, 0xac, 0x02, 0xf0, 0xb1, 0x0a, 0xc0, 0xf3, 0x3a, 0x70,
	0x16, 0xeb, 0xc0, 0x79, 0x5f, 0x07, 0xce, 0x4d, 0x3b, 0x9e, 0xa8, 0xb1, 0xa6, 0x28, 0x12, 0x09,
	0x2e, 0x46, 0xee, 0xf0, 0x59, 0x89, 0xf8, 0x11, 0xff, 0xf9, 0x16, 0x95, 0xa7, 0x4c, 0xd2, 0x6a,
	0x59, 0xf2, 0xe4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x32, 0x98, 0x2a, 0xac, 0xb3, 0x01, 0x00, 0x00,
}

func (m *SmartAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SmartAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SmartAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintAccount(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x20
	}
	if m.AccountNumber != 0 {
		i = encodeVarintAccount(dAtA, i, uint64(m.AccountNumber))
		i--
		dAtA[i] = 0x18
	}
	if m.PubKey != nil {
		{
			size, err := m.PubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAccount(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAccount(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SmartAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAccount(uint64(l))
	}
	if m.PubKey != nil {
		l = m.PubKey.Size()
		n += 1 + l + sovAccount(uint64(l))
	}
	if m.AccountNumber != 0 {
		n += 1 + sovAccount(uint64(m.AccountNumber))
	}
	if m.Sequence != 0 {
		n += 1 + sovAccount(uint64(m.Sequence))
	}
	return n
}

func sovAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAccount(x uint64) (n int) {
	return sovAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SmartAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SmartAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SmartAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKey == nil {
				m.PubKey = &types.Any{}
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountNumber", wireType)
			}
			m.AccountNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccount = fmt.Errorf("proto: unexpected end of group")
)
