// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: distribution/epoch_vote_info.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorEpochVoteInfo struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	ProposerBlocks   int64  `protobuf:"varint,2,opt,name=proposer_blocks,json=proposerBlocks,proto3" json:"proposer_blocks,omitempty"`
	ActiveBlocks     int64  `protobuf:"varint,3,opt,name=active_blocks,json=activeBlocks,proto3" json:"active_blocks,omitempty"`
	AccPower         int64  `protobuf:"varint,4,opt,name=acc_power,json=accPower,proto3" json:"acc_power,omitempty"`
}

func (m *ValidatorEpochVoteInfo) Reset()         { *m = ValidatorEpochVoteInfo{} }
func (m *ValidatorEpochVoteInfo) String() string { return proto.CompactTextString(m) }
func (*ValidatorEpochVoteInfo) ProtoMessage()    {}
func (*ValidatorEpochVoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d863eda70fc0a961, []int{0}
}
func (m *ValidatorEpochVoteInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorEpochVoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorEpochVoteInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorEpochVoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEpochVoteInfo.Merge(m, src)
}
func (m *ValidatorEpochVoteInfo) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorEpochVoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEpochVoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEpochVoteInfo proto.InternalMessageInfo

func (m *ValidatorEpochVoteInfo) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValidatorEpochVoteInfo) GetProposerBlocks() int64 {
	if m != nil {
		return m.ProposerBlocks
	}
	return 0
}

func (m *ValidatorEpochVoteInfo) GetActiveBlocks() int64 {
	if m != nil {
		return m.ActiveBlocks
	}
	return 0
}

func (m *ValidatorEpochVoteInfo) GetAccPower() int64 {
	if m != nil {
		return m.AccPower
	}
	return 0
}

type EpochVotesInfo struct {
	Validators []ValidatorEpochVoteInfo `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators"`
}

func (m *EpochVotesInfo) Reset()         { *m = EpochVotesInfo{} }
func (m *EpochVotesInfo) String() string { return proto.CompactTextString(m) }
func (*EpochVotesInfo) ProtoMessage()    {}
func (*EpochVotesInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d863eda70fc0a961, []int{1}
}
func (m *EpochVotesInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochVotesInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochVotesInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochVotesInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochVotesInfo.Merge(m, src)
}
func (m *EpochVotesInfo) XXX_Size() int {
	return m.Size()
}
func (m *EpochVotesInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochVotesInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EpochVotesInfo proto.InternalMessageInfo

func (m *EpochVotesInfo) GetValidators() []ValidatorEpochVoteInfo {
	if m != nil {
		return m.Validators
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidatorEpochVoteInfo)(nil), "auranw.aura.distribution.ValidatorEpochVoteInfo")
	proto.RegisterType((*EpochVotesInfo)(nil), "auranw.aura.distribution.EpochVotesInfo")
}

func init() {
	proto.RegisterFile("distribution/epoch_vote_info.proto", fileDescriptor_d863eda70fc0a961)
}

var fileDescriptor_d863eda70fc0a961 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x27, 0xb6, 0x88, 0x8d, 0x5a, 0x75, 0x10, 0x19, 0x14, 0x62, 0xa9, 0x0b, 0x0b, 0x6a,
	0x46, 0xf4, 0x04, 0x16, 0x14, 0xdc, 0x49, 0x17, 0x5d, 0xb8, 0x19, 0x32, 0x99, 0xb4, 0x0d, 0xd6,
	0x79, 0x21, 0x49, 0x5b, 0xbd, 0x85, 0x47, 0xf1, 0x18, 0x5d, 0x76, 0xe9, 0x4a, 0xa4, 0xbd, 0x88,
	0x24, 0x75, 0x86, 0x0a, 0xba, 0x7a, 0xc9, 0xff, 0x3e, 0x5e, 0xfe, 0xfc, 0x0f, 0x37, 0x33, 0x69,
	0xac, 0x96, 0xe9, 0xc8, 0x4a, 0xc8, 0x63, 0xa1, 0x80, 0x0f, 0x92, 0x31, 0x58, 0x91, 0xc8, 0xbc,
	0x07, 0x54, 0x69, 0xb0, 0x10, 0x46, 0x6c, 0xa4, 0x59, 0x3e, 0xa1, 0xae, 0xd0, 0x55, 0xfe, 0x70,
	0xbf, 0x0f, 0x7d, 0xf0, 0x50, 0xec, 0x4e, 0x4b, 0xbe, 0xf9, 0x8e, 0xf0, 0x41, 0x97, 0x0d, 0x65,
	0xc6, 0x2c, 0xe8, 0x5b, 0x37, 0xb2, 0x0b, 0x56, 0xdc, 0xe7, 0x3d, 0x08, 0xcf, 0xf0, 0xde, 0xb8,
	0xe8, 0x24, 0x2c, 0xcb, 0xb4, 0x30, 0x26, 0x42, 0x0d, 0xd4, 0xaa, 0x75, 0x76, 0xcb, 0xc6, 0xcd,
	0x52, 0x0f, 0x4f, 0xf1, 0x8e, 0xd2, 0xa0, 0xc0, 0x08, 0x9d, 0xa4, 0x43, 0xe0, 0x4f, 0x26, 0x5a,
	0x6b, 0xa0, 0x56, 0xa5, 0x53, 0x2f, 0xe4, 0xb6, 0x57, 0xc3, 0x13, 0xbc, 0xcd, 0xb8, 0x95, 0x63,
	0x51, 0x60, 0x15, 0x8f, 0x6d, 0x2d, 0xc5, 0x1f, 0xe8, 0x08, 0xd7, 0x18, 0xe7, 0x89, 0x82, 0x89,
	0xd0, 0x51, 0xd5, 0x03, 0x1b, 0x8c, 0xf3, 0x07, 0x77, 0x6f, 0x0e, 0x70, 0xbd, 0x34, 0x6a, 0xbc,
	0xd3, 0x2e, 0xc6, 0xa5, 0x21, 0x67, 0xb1, 0xd2, 0xda, 0xbc, 0xba, 0xa4, 0xff, 0x25, 0x41, 0xff,
	0xfe, 0x6f, 0xbb, 0x3a, 0xfd, 0x3c, 0x0e, 0x3a, 0x2b, 0x93, 0xda, 0x77, 0xd3, 0x39, 0x41, 0xb3,
	0x39, 0x41, 0x5f, 0x73, 0x82, 0xde, 0x16, 0x24, 0x98, 0x2d, 0x48, 0xf0, 0xb1, 0x20, 0xc1, 0xe3,
	0x79, 0x5f, 0xda, 0xc1, 0x28, 0xa5, 0x1c, 0x9e, 0x63, 0xf7, 0xc0, 0x45, 0x3e, 0xf1, 0x35, 0x7e,
	0x89, 0x7f, 0x2d, 0xc9, 0xbe, 0x2a, 0x61, 0xd2, 0x75, 0x9f, 0xf5, 0xf5, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x45, 0xb9, 0x8d, 0x26, 0xc1, 0x01, 0x00, 0x00,
}

func (m *ValidatorEpochVoteInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorEpochVoteInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorEpochVoteInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccPower != 0 {
		i = encodeVarintEpochVoteInfo(dAtA, i, uint64(m.AccPower))
		i--
		dAtA[i] = 0x20
	}
	if m.ActiveBlocks != 0 {
		i = encodeVarintEpochVoteInfo(dAtA, i, uint64(m.ActiveBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.ProposerBlocks != 0 {
		i = encodeVarintEpochVoteInfo(dAtA, i, uint64(m.ProposerBlocks))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintEpochVoteInfo(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochVotesInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochVotesInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochVotesInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEpochVoteInfo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintEpochVoteInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovEpochVoteInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorEpochVoteInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovEpochVoteInfo(uint64(l))
	}
	if m.ProposerBlocks != 0 {
		n += 1 + sovEpochVoteInfo(uint64(m.ProposerBlocks))
	}
	if m.ActiveBlocks != 0 {
		n += 1 + sovEpochVoteInfo(uint64(m.ActiveBlocks))
	}
	if m.AccPower != 0 {
		n += 1 + sovEpochVoteInfo(uint64(m.AccPower))
	}
	return n
}

func (m *EpochVotesInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovEpochVoteInfo(uint64(l))
		}
	}
	return n
}

func sovEpochVoteInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEpochVoteInfo(x uint64) (n int) {
	return sovEpochVoteInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorEpochVoteInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpochVoteInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorEpochVoteInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorEpochVoteInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpochVoteInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpochVoteInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerBlocks", wireType)
			}
			m.ProposerBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposerBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveBlocks", wireType)
			}
			m.ActiveBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccPower", wireType)
			}
			m.AccPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEpochVoteInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpochVoteInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochVotesInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpochVoteInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochVotesInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochVotesInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpochVoteInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpochVoteInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, ValidatorEpochVoteInfo{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpochVoteInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpochVoteInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEpochVoteInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEpochVoteInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpochVoteInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEpochVoteInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEpochVoteInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEpochVoteInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEpochVoteInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEpochVoteInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEpochVoteInfo = fmt.Errorf("proto: unexpected end of group")
)
